//
// Created by hansono_bn3monkey on 2024-10-22.
//

#ifndef ANDROIDNATIVELIBRARYCHANNEL_DATASOURCELIBRARYVERSION_HPP
#define ANDROIDNATIVELIBRARYCHANNEL_DATASOURCELIBRARYVERSION_HPP

#define DATASOURCELIBRARY_MAJOR_VERSION 2
#define DATASOURCELIBRARY_MINOR_VERSION 0
#define DATASOURCELIBRARY_REVISION_VERSION 0

#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)

#define DATASOURCELIBRARY_VERSION_STRING TOSTRING(DATASOURCELIBRARY_MAJOR_VERSION) "." TOSTRING(DATASOURCELIBRARY_MINOR_VERSION) "." TOSTRING(DATASOURCELIBRARY_REVISION_VERSION)

#endif //ANDROIDNATIVELIBRARYCHANNEL_DataSourceLibraryVERSION_HPP
