//
// Created by hansono_bn3monkey on 2024-10-22.
//

#ifndef ANDROIDNATIVELIBRARYCHANNEL_SERVERLIBRARYVERSION_HPP
#define ANDROIDNATIVELIBRARYCHANNEL_SERVERLIBRARYVERSION_HPP

#define SERVERLIBRARY_MAJOR_VERSION 2
#define SERVERLIBRARY_MINOR_VERSION 0
#define SERVERLIBRARY_REVISION_VERSION 0

#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)

#define SERVERLIBRARY_VERSION_STRING TOSTRING(SERVERLIBRARY_MAJOR_VERSION) "." TOSTRING(SERVERLIBRARY_MINOR_VERSION) "." TOSTRING(SERVERLIBRARY_REVISION_VERSION)

#endif //ANDROIDNATIVELIBRARYCHANNEL_SERVERLIBRARYVERSION_HPP
